### ISSUE TITLE
Add instructions on how to add blog posts

### ISSUE THREAD

**Issue by jeid64** [decause/hfoss#19]
Hey, I don't think there are instructions on how to add blog posts and lightning talks to the Participants page for your YAML file. The only thing first flight says is to write your first blog post, but it doesn't say to add it to your YAML file.

**Comment by liam-middlebrook** [comment]
This seems like a reasonable request. For the record most of the time @decause will just tell the class (and the TA) the YAML key that the blog post should be tagged with.

An example YAML with firstflight turned in should be

```
blog: http://fsf.org
feed: http://blog.com/rss.xml
forges:
- http://github.com/username
irc: username
name: Thunder Dome
rit_dce: abc123
hw:
  firstflight: http://google.com
```

**Comment by Nolski** [comment]
``` yaml
blog: http://fsf.org
feed: http://blog.com/rss.xml
forges: # This is a list
  - http://github.com/username
irc: username
name: Thunder Dome
rit_dce: abc123
lightningtalkN: http://nolski.rocks/talkthing
hw: # This is  a dictionary (key value)
  firstflight: http://google.com
```
